<!-- Generated by Copilot -->
<template>
  
  <div class="dataset-plot-container">
    <div class="dataset-plot-plot-container-plot" v-if="foldedDatasets.length > 0">
      <folded-plotly-graph
        :datasets="foldedDatasets.map(d => d.plotlyDatasets![1])"
        :show-errors="props.showErrors"
        :colors="foldedDatasets.map(d => (d.customColor ?? d.region.color))"
        :data-options="ddataOptions"
        :names="foldedDatasets.map(d => d.name ?? d.id)"
        :layout-options="dlayoutOptions"
        :fold-type="foldedDatasets[0].folded?.foldType"
        :timezones="foldedDatasets.map(d => d.folded.timezone ?? 'UTC')"
        :config-options="dconfigOptions"
      />
    </div>
    <div class="dataset-plot-plot-container-plot" v-if="normalDatasets.length > 0">
      <plotly-graph
        :datasets="normalDatasets.map(d => userDatasetToPlotly(d, true))"
        :colors="normalDatasets.map(d => (d.customColor || d.region.color))"
        :show-errors="showErrors"
        :data-options="ddataOptions"
        :names="normalDatasets.map(d => d.name ?? d.id)"
        :layout-options="{
          ...dlayoutOptions,
          xaxis: {...(dlayoutOptions?.xaxis ?? {}), title: {text: 'Local Time for Region'}},
        }"
        :config-options="dconfigOptions"
      />
    </div>
      
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import FoldedPlotlyGraph from '../FoldedPlotlyGraph.vue';
import type {FoldedPlotlyGraphProps} from '../FoldedPlotlyGraph.vue';
import PlotlyGraph from './PlotlyGraph.vue';
import { userDatasetToPlotly } from '@/utils/data_converters';
import type { UserDataset } from '@/types';
import type { Config, ModeBarDefaultButtons } from 'plotly.js-dist-min';


interface DatasetPlotProps extends Omit<FoldedPlotlyGraphProps, 'datasets'| 'foldType' | 'timezones'> {
  datasets: UserDataset[];
  hideLegend?: boolean;
}
const props = defineProps<DatasetPlotProps>();

// Common layout options for all plots
const dlayoutOptions = {
  margin: { t: 20, r: 30, b: 60, l: 80 },
  autosize: true,
  ...(props.layoutOptions ?? {}),
};

// Common config options for all plots
const dconfigOptions: Partial<Config> = {
  responsive: true,
  modeBarButtonsToRemove: ['sendDataToCloud', 'lasso2d', 'resetScale2d'] as ModeBarDefaultButtons[],
  ...(props.configOptions ?? {}),
};

const ddataOptions = computed(() => {
  const defaultOpt = {showlegend: props.hideLegend ?? false};
  if (props.dataOptions && props.dataOptions.length > 0) {
    return props.dataOptions.map((opt) => ({...opt, ...defaultOpt}));
  } else {
    return [{...defaultOpt}];
  }
});

const foldedDatasets = computed(() => {
  return props.datasets.filter(d => d.folded && d.plotlyDatasets);
});

const normalDatasets = computed(() => {
  return props.datasets.filter(d => !d.folded);
});


</script>

<style>

div.dataset-plot-plot-container {
  display: flex;
  flex: 1 0 auto;
  justify-content: center;
  gap: 1rem;
  width: 100%;
}

div.dataset-plot-plot-container-plot {
  width: 100%;
}


div.dataset-plot-container {
  width: 100%;
}

div.dataset-plot-plot-container {
  width: 100%;
}

div.dataset-plot-plot-container-plot {
  width: 100%;
}

/* Generated by Copilot - Ensure child components fill width */
div.dataset-plot-container :deep(.js-plotly-plot) {
  width: 100% !important;
}

div.dataset-plot-container :deep(.js-plotly-plot .plot-container) {
  width: 100% !important;
}

div.dataset-plot-container :deep(.js-plotly-plot .svg-container) {
  width: 100% !important;
}
</style>