<!-- Generated by Copilot -->
<template>    
    <div class="multi-plot-container">
      
      <div class="multi-plot-plot-container"  v-for="group in datasetsGroupedByMolecule" :key="group[0]">
        
        <DatasetPlot
          :datasets="group[1]"
          :show-errors="true"
          :data-options="[{mode: 'markers'}]"
          hide-legend
          :layout-options="commonLayoutOptions"
          :config-options="commonConfigOptions"
        />
      </div>
      <!-- <div  class="multi-plot-plot-container" v-for="(dataset, index) in datasets" :key="index">
        
        <h3>{{ dataset.name || `Dataset ${index + 1}` }}</h3>
        <DatasetPlot
          :datasets="[dataset]"
          :show-errors="showErrorBands[index]"
          hide-legend
          :layout-options="commonLayoutOptions"
          :config-options="commonConfigOptions"
        />
      
      </div>
       -->
    </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
// import FoldedPlotlyGraph from '../FoldedPlotlyGraph.vue';
// import PlotlyGraph from './PlotlyGraph.vue';
// import { userDatasetToPlotly } from '@/utils/data_converters';
import type { UserDataset } from '@/types';
import type { Config, ModeBarDefaultButtons } from 'plotly.js-dist-min';
import DatasetPlot from './DatasetPlot.vue';

interface MultiPlotProps {
  datasets: UserDataset[];
}

const { datasets } = defineProps<MultiPlotProps>();

const _showErrorBands = ref(datasets.map((d) => d.folded ? true : false));

// Common layout options for all plots
const commonLayoutOptions=  {
  margin: { t: 30, r: 30, b: 60, l: 80, autoexpand: true, },
  autosize: true,
  height: 250,
  width: undefined,
  xaxis: {
    gridcolor: 'rgba(128, 128, 128, 0.3)',
  },
  yaxis: {
    gridcolor: 'rgba(128, 128, 128, 0.3)',
  },
  legend: {
    y: 1.3, 
    orientation:'h' as |'h' | 'v',
    bordercolor: '#ccc', 
    borderwidth:1,
    entrywidthmode: 'fraction',
    entrywidth: 0.3, 
  }
};

// Common config options for all plots
const commonConfigOptions: Partial<Config> = {
  responsive: true,
  modeBarButtonsToRemove: ['sendDataToCloud', 'lasso2d', 'resetScale2d'] as ModeBarDefaultButtons[],
};

// const groupByMolecule = ref(false);

const datasetsGroupedByMolecule = computed(() => {
  const groups = new Map<string, UserDataset[]>();
  datasets.forEach((dataset) => {
    const molecule = dataset.molecule || 'Unknown Molecule';
    if (!groups.has(molecule)) {
      groups.set(molecule, []);
    }
    groups.get(molecule)!.push(dataset);
  });
  return groups;
});


</script>

<style>
div.multi-plot-container {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  overflow-y: auto;
  height: calc(90vh - 100px);
  align-items: center;
  width: 100%;
  outline: 1px solid white;;
}

div.multi-plot-plot-container {
  width: 90%;
  outline: 1px solid cyan;
}

div.multi-plot-plot-container-plot {
  outline: 1px solid magenta;
}

/* Add this to ensure DatasetPlot fills container */
div.multi-plot-plot-container :deep(.js-plotly-plot) {
  outline: 5px solid red;
}


</style>